  include "../constants.asm"
  org #0000
ToPStartSong:
  db 7,184
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 30
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 1
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 18
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 2
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 13
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1 + MUSIC_CMD_TIME_STEP_FLAG, 30
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1 + MUSIC_CMD_TIME_STEP_FLAG, 30
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 32
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 19
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 14
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1 + MUSIC_CMD_TIME_STEP_FLAG, 33
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 36
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 18
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 13
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 37
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 19
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 14
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 41
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 18
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3 + MUSIC_CMD_TIME_STEP_FLAG, 15
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_SQUARE_WAVE, 0
  db 8, 0
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_SQUARE_WAVE, 1
  db 9, 0
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_SQUARE_WAVE, 2
  db 10, 0
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_END
